### ISSUE TITLE
BLACKLIST

### ISSUE THREAD

**Issue by SalazahrR** [zerolend/governance#55]
hi DEVS in general, I have three demands, I had my wallet stolen, but they were ZEROvp, from EARLYZERO, so I still have up to 60% vesting, my wallet 0xAE883c17d92f4B98Ca80378D481D3dA91D18C111, from the thief 0x35Fe51f473D6871E28b066cd30C2d09E259b5f24, my wallet 0xb292be9e0803930cfa361daa024fc86bb7e656d6 is on the blacklist, and another demand is that I am trying to report a serious failure that I managed to try to win the immunofi prize, but I am not succeeding, can I Help me with these 3 demands, please?

**Comment by jecobeLiwes** [comment]
@SalazahrR For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [ZEROLEND SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by SalazahrR** [comment]
my wallet 0xb292be9e0803930cfa361daa024fc86bb7e656d6 is on the blacklist, and another demand is that I am trying to report a serious failure that I managed to try to win the immunofi prize, but I am not succeeding, can I Help me with these 3 demands, please?
![Screenshot (335)](https://github.com/user-attachments/assets/ffb6f20f-e061-4a70-92be-a040162747e1)
