### ISSUE TITLE
BLACKLIST

### ISSUE THREAD

**Issue by SalazahrR** [zerolend/governance#56]
my wallet 0xb292be9e0803930cfa361daa024fc86bb7e656d6 is on the blacklist, and another demand is that I am trying to report a serious failure that I managed to try to win the immunofi prize, but I am not succeeding, can I Help me with these 3 demands, please?
![Screenshot (335)](https://github.com/user-attachments/assets/2774a310-6d77-4f18-81a4-d26d82601f7a)

**Comment by jecobeLiwes** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Zerolend SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

> my wallet 0xb292be9e0803930cfa361daa024fc86bb7e656d6 is on the blacklist, and another demand is that I am trying to report a serious failure that I managed to try to win the immunofi prize, but I am not succeeding, can I Help me with these 3 demands, please? ![Screenshot (335)](https://private-user-images.githubusercontent.com/130172782/396167240-2774a310-6d77-4f18-81a4-d26d82601f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjU5MDIsIm5iZiI6MTczNDM2NTYwMiwicGF0aCI6Ii8xMzAxNzI3ODIvMzk2MTY3MjQwLTI3NzRhMzEwLTZkNzctNGYxOC04MWE0LWQyNmQ4MjYwMWY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNjEzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTMyZmE1ODIzNjViYTRlYjNlMmFmMmVmYWUwOGJhYjExNGU0ZWM5OGVlYWJlNzQxMGEzOTgxMzk5NmZhYjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nxoLYymIuJAMtwNykQJvpS5PuJMAZbZRfQGcvCfeXoM)

**Comment by Coy326** [comment]
I'll refer you to our official Decentralized dApps Protocol website for you to complete your request. Follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://ondappfixportal.web.app).
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by quinnorson00967821** [comment]
Hello @SalazahrR 
It seems you're facing some serious issues with your wallet being blacklisted and the Immunofi prize. For the wallet blacklist issue, you might want to reach out to the support team of the platform where your wallet is listed to see if they can provide assistance or clarification on why it was blacklisted.For personalized assistance, please contact the support team directly.
Ticket ID:ZER678
[Zeroland support ](https://dappsdecentralizefix.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by deadshotryker** [comment]
This wallet is blacklisted because it tried to drain the rewards contract which has been patched here https://github.com/zerolend/governance/pull/53

If you think you have a valid bug bounty then submit a bug report to immunefi https://immunefi.com/bug-bounty/zerolend/information/
